// @ts-check
// Generated by AI Test Modernization Platform — blueprint playwright-js-v1
// Timeouts mirror the legacy config.properties (explicitWaitSeconds, pageLoadTimeoutSeconds).
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  // Live third-party site: run serially to stay polite and stable.
  fullyParallel: false,
  workers: 1,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  timeout: 180_000,
  expect: { timeout: 15000 },
  reporter: [
    ['html', { open: 'never' }],
    ['json', { outputFile: 'test-results/results.json' }],
  ],
  use: {
    baseURL: "https://www.myprime.com",
    actionTimeout: 15000,
    navigationTimeout: 30000,
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
    { name: 'firefox', use: { ...devices['Desktop Firefox'] } },
    { name: 'webkit', use: { ...devices['Desktop Safari'] } },
  ],
});
