// @ts-check
// Generated by AI Test Modernization Platform — blueprint playwright-js-v1
// Source: selenium-framework/src/test/resources/config.properties
export const config = {
  baseUrl: "https://www.myprime.com",
  explicitWaitSeconds: 15,
  pageLoadTimeoutSeconds: 30,
  healthPlan: "BCBS Alabama",
  isMedicarePartD: "No",
  drugList: "SourceRx 1.0 Drug Guide",
};
