// @ts-check
// Generated by AI Test Modernization Platform — blueprint playwright-js-v1
// Source: selenium-framework/src/test/java/com/myprime/automation/tests/BaseTest.java (helper:BaseTest.goToFindMedicinesAsGuest)
import { test as base, expect } from '@playwright/test';
import { config } from '../config/framework-config.js';
import { HomePage } from '../pages/home-page.js';
import { MedicineSearchPage } from '../pages/medicine-search-page.js';
import { PlanSelectorModal } from '../pages/plan-selector-modal.js';

export const test = base.extend({
  /**
   * Drives the non-signed-in entry flow: home -> "explore MyPrime without
   * signing in" -> pick the configured health plan -> land on Find medicines
   * with the configured drug list applied. Every test starts from here.
   */
  medicineSearchPage: async ({ page }, use) => {
    const homePage = new HomePage(page);
    await homePage.open();
    const planSelectorModal = await homePage.clickExploreMyPrimeWithoutSigningIn();
    const homePage2 = await planSelectorModal.selectPlanAndContinue(config.healthPlan, config.isMedicarePartD);
    const medicineSearchPage = new MedicineSearchPage(page);
    await medicineSearchPage.open();
    await medicineSearchPage.selectDrugList(config.drugList);
    await use(medicineSearchPage);
  },
});

export { expect };
