// @ts-check
// Generated by AI Test Modernization Platform — blueprint playwright-js-v1
// Source: selenium-framework/src/main/java/com/myprime/automation/pages/HomePage.java
/**
 * https://www.myprime.com/ landing page, unauthenticated state.
 */
import { BasePage } from './base-page.js';
import { PlanSelectorModal } from './plan-selector-modal.js';

export class HomePage extends BasePage {
  /** @param {import('@playwright/test').Page} page */
  constructor(page) {
    super(page);
    // .first(): Selenium By-locators resolve to the first match; the AUT even
    // ships duplicate ids, so keep that semantic instead of strict mode.
    this.exploreMyprimeLink = page.locator("//a[normalize-space(text())='explore MyPrime']").first();
  }

  async open() {
    await this.page.goto("/");
    return this;
  }

  /**
   * Clicks "Or select a plan and explore MyPrime without signing in." which
   * opens the health-plan-selection modal.
   */
  async clickExploreMyPrimeWithoutSigningIn() {
    await this.exploreMyprimeLink.click();
    return new PlanSelectorModal(this.page);
  }
}
